# -*- coding: utf-8 -*-
"""Matplotlib.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/103WFmXGdb_207F_YLHGPvsl4uWGBz9OP

# **Format Strings in Plot Function**
"""

# Commented out IPython magic to ensure Python compatibility.
import matplotlib.pyplot as plt
import numpy as np

# %matplotlib inline

x = [1,2,3,4,5,6,7]
y = [60,50,68,78,32,67,54]

plt.plot(x,y, 'bD--')

#using keywords
# you can select any color using hex code.
plt.plot(x,y, color='red', marker = 'D', linestyle= '', markersize = 10)

#alpha is used to control transperancy
#0-unvisible, 1- visible, 0.5 - light visible
plt.plot(x,y,color='black', alpha=0.5)

"""# **Axes labels, legend and Grid**"""

days = [1,2,3,4,5,6,7]
max_s = [200,240,220,345,568,290,230]
min_s = [190,210,180,300,500,180,200]
avg_s = [195,225,200,323,535,235,215]

plt.xlabel("Days")
plt.ylabel("Spent")
#plt.title("Week")

plt.plot(days,max_s, label="Max")
plt.plot(days,min_s, label = "Min")
plt.plot(days,avg_s, label = "Avg")


plt.legend(loc="best", shadow=True)
#loc -> means you can enter custom position according to you. 

#plt.grid()
#means it will show grid lines horizontally & vertically.

"""# **Bar Chart**"""

company = ['Meta', 'Amazon', 'Apple', 'Netflix' , 'Google']
employees = [18, 25, 20, 15, 23]
profit=[14,22,10,12,18]

xpos= np.arange(len(company))
xpos

plt.xticks(xpos,company)
plt.ylabel("employees(bin)")
plt.title("MAANG")
plt.bar(xpos-0.2,employees, width=0.4, label= "Employees")
plt.bar(xpos+0.2,profit,width=0.4 ,label="Profit")
plt.legend(loc="besx")

plt.yticks(xpos,company)
plt.ylabel("employees(bin)")
plt.title("MAANG")
plt.barh(xpos-0.2,employees, label= "Employees")
plt.barh(xpos+0.2,profit,label="Profit")
plt.legend(loc="best")

"""# **Histograms**"""

cancer_men_deaths = [140,150,170,155,125,148,159,175,180,138]
cancer_women_deaths = [120,140,160,145,115,138,165,160,120,135]

plt.xlabel('Death Range')
plt.ylabel('Days')
plt.title('Cancer Deaths')
plt.hist([cancer_men_deaths, cancer_women_deaths], bins=[125,140,160,180], rwidth=0.85, color=['blue', 'orange'], 
         label = ['men', 'women'])
plt.legend()

cancer_men_deaths = [140,150,170,155,125,148,159,175,180,138]
cancer_women_deaths = [120,140,160,145,115,138,165,160,120,135]

plt.xlabel('Death Range')
plt.ylabel('Days')
plt.title('Cancer Deaths')
plt.hist([cancer_men_deaths, cancer_women_deaths], bins=[125,140,160,180], rwidth=0.85, color=['blue', 'orange'], 
         label = ['men', 'women'], orientation = 'horizontal')
plt.legend()

"""# **Pie Chart**"""

exp_values = [885,740,215,1640]
exp_cate = ['Daily', 'Veg/Fruits', 'Paneer/Eggs', 'Ration']

plt.pie(exp_values, labels= exp_cate, radius = 1.5, autopct = '%0.1f%%', startangle=45)
plt.show()

#explode = [0,0.1,0.1,0,0]
#startangle=45

"""# **Save Chart to a File  Using savefig**"""

plt.pie(exp_values, labels= exp_cate, radius = 1.5, autopct = '%0.1f%%', startangle=90)
plt.show()

plt.savefig ("piechart.png", bbox_inches="tight", pad_inches=2, transparent = True)